ACTORS = {'exp0': {'DIM': (16, 16),
          'POS': (288, 208),
          'name': 'exp0',
          'offsetkey': 'exp',
          'scripts': 'exp',
          'sprites': 'exp',
          'tangible': False},
 'health_bar_segment0': {'DIM': (64, 16),
                         'POS': (-96, 528),
                         'name': 'health_bar_segment0',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment1': {'DIM': (64, 16),
                         'POS': (-32, 528),
                         'name': 'health_bar_segment1',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment10': {'DIM': (64, 16),
                          'POS': (544, 528),
                          'name': 'health_bar_segment10',
                          'offsetkey': 'health_bar_segment',
                          'scripts': 'health_bar_segment',
                          'sprites': 'health_bar_segment',
                          'tangible': False},
 'health_bar_segment11': {'DIM': (64, 16),
                          'POS': (608, 528),
                          'name': 'health_bar_segment11',
                          'offsetkey': 'health_bar_segment',
                          'scripts': 'health_bar_segment',
                          'sprites': 'health_bar_segment',
                          'tangible': False},
 'health_bar_segment12': {'DIM': (64, 16),
                          'POS': (672, 528),
                          'name': 'health_bar_segment12',
                          'offsetkey': 'health_bar_segment',
                          'scripts': 'health_bar_segment',
                          'sprites': 'health_bar_segment',
                          'tangible': False},
 'health_bar_segment13': {'DIM': (64, 16),
                          'POS': (736, 528),
                          'name': 'health_bar_segment13',
                          'offsetkey': 'health_bar_segment',
                          'scripts': 'health_bar_segment',
                          'sprites': 'health_bar_segment',
                          'tangible': False},
 'health_bar_segment14': {'DIM': (64, 16),
                          'POS': (800, 528),
                          'name': 'health_bar_segment14',
                          'offsetkey': 'health_bar_segment',
                          'scripts': 'health_bar_segment',
                          'sprites': 'health_bar_segment',
                          'tangible': False},
 'health_bar_segment15': {'DIM': (64, 16),
                          'POS': (864, 528),
                          'name': 'health_bar_segment15',
                          'offsetkey': 'health_bar_segment',
                          'scripts': 'health_bar_segment',
                          'sprites': 'health_bar_segment',
                          'tangible': False},
 'health_bar_segment16': {'DIM': (64, 16),
                          'POS': (928, 528),
                          'name': 'health_bar_segment16',
                          'offsetkey': 'health_bar_segment',
                          'scripts': 'health_bar_segment',
                          'sprites': 'health_bar_segment',
                          'tangible': False},
 'health_bar_segment17': {'DIM': (64, 16),
                          'POS': (992, 528),
                          'name': 'health_bar_segment17',
                          'offsetkey': 'health_bar_segment',
                          'scripts': 'health_bar_segment',
                          'sprites': 'health_bar_segment',
                          'tangible': False},
 'health_bar_segment2': {'DIM': (64, 16),
                         'POS': (32, 528),
                         'name': 'health_bar_segment2',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment3': {'DIM': (64, 16),
                         'POS': (96, 528),
                         'name': 'health_bar_segment3',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment4': {'DIM': (64, 16),
                         'POS': (160, 528),
                         'name': 'health_bar_segment4',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment5': {'DIM': (64, 16),
                         'POS': (224, 528),
                         'name': 'health_bar_segment5',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment6': {'DIM': (64, 16),
                         'POS': (288, 528),
                         'name': 'health_bar_segment6',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment7': {'DIM': (64, 16),
                         'POS': (352, 528),
                         'name': 'health_bar_segment7',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment8': {'DIM': (64, 16),
                         'POS': (416, 528),
                         'name': 'health_bar_segment8',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'health_bar_segment9': {'DIM': (64, 16),
                         'POS': (480, 528),
                         'name': 'health_bar_segment9',
                         'offsetkey': 'health_bar_segment',
                         'scripts': 'health_bar_segment',
                         'sprites': 'health_bar_segment',
                         'tangible': False},
 'nme0': {'DIM': (32, 32),
          'POS': (0, 48),
          'name': 'nme0',
          'offsetkey': 'nme',
          'scripts': 'nme',
          'sprites': 'nme',
          'tangible': True},
 'nmeManager0': {'DIM': (16, 16),
                 'POS': (848, 96),
                 'name': 'nmeManager0',
                 'offsetkey': 'nmeManager',
                 'scripts': 'nmeManager',
                 'sprites': 'nmeManager',
                 'tangible': False},
 'nmeRelocator0': {'DIM': (64, 768),
                   'POS': (1120, -144),
                   'name': 'nmeRelocator0',
                   'offsetkey': 'nmeRelocator',
                   'scripts': 'nmeRelocator',
                   'sprites': 'nmeRelocator',
                   'tangible': False},
 'nmeRelocator1': {'DIM': (1280, 64),
                   'POS': (-160, -208),
                   'name': 'nmeRelocator1',
                   'offsetkey': 'nmeRelocator',
                   'scripts': 'nmeRelocator',
                   'sprites': 'nmeRelocator',
                   'tangible': False},
 'nmeRelocator2': {'DIM': (64, 768),
                   'POS': (-224, -144),
                   'name': 'nmeRelocator2',
                   'offsetkey': 'nmeRelocator',
                   'scripts': 'nmeRelocator',
                   'sprites': 'nmeRelocator',
                   'tangible': False},
 'nmeRelocator3': {'DIM': (1280, 64),
                   'POS': (-160, 624),
                   'name': 'nmeRelocator3',
                   'offsetkey': 'nmeRelocator',
                   'scripts': 'nmeRelocator',
                   'sprites': 'nmeRelocator',
                   'tangible': False},
 'nmeSpawner0': {'DIM': (16, 16),
                 'POS': (-128, -64),
                 'name': 'nmeSpawner0',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner1': {'DIM': (16, 16),
                 'POS': (-64, -112),
                 'name': 'nmeSpawner1',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner10': {'DIM': (16, 16),
                  'POS': (512, -112),
                  'name': 'nmeSpawner10',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner11': {'DIM': (16, 16),
                  'POS': (576, -112),
                  'name': 'nmeSpawner11',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner12': {'DIM': (16, 16),
                  'POS': (640, -112),
                  'name': 'nmeSpawner12',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner13': {'DIM': (16, 16),
                  'POS': (1024, -112),
                  'name': 'nmeSpawner13',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner14': {'DIM': (16, 16),
                  'POS': (704, -112),
                  'name': 'nmeSpawner14',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner15': {'DIM': (16, 16),
                  'POS': (768, -112),
                  'name': 'nmeSpawner15',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner16': {'DIM': (16, 16),
                  'POS': (832, -112),
                  'name': 'nmeSpawner16',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner17': {'DIM': (16, 16),
                  'POS': (896, -112),
                  'name': 'nmeSpawner17',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner18': {'DIM': (16, 16),
                  'POS': (960, -112),
                  'name': 'nmeSpawner18',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner19': {'DIM': (16, 16),
                  'POS': (1072, -80),
                  'name': 'nmeSpawner19',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner2': {'DIM': (16, 16),
                 'POS': (0, -112),
                 'name': 'nmeSpawner2',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner20': {'DIM': (16, 16),
                  'POS': (1072, -16),
                  'name': 'nmeSpawner20',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner21': {'DIM': (16, 16),
                  'POS': (1072, 48),
                  'name': 'nmeSpawner21',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner22': {'DIM': (16, 16),
                  'POS': (1072, 112),
                  'name': 'nmeSpawner22',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner23': {'DIM': (16, 16),
                  'POS': (1072, 176),
                  'name': 'nmeSpawner23',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner24': {'DIM': (16, 16),
                  'POS': (1072, 240),
                  'name': 'nmeSpawner24',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner25': {'DIM': (16, 16),
                  'POS': (1072, 304),
                  'name': 'nmeSpawner25',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner26': {'DIM': (16, 16),
                  'POS': (1072, 368),
                  'name': 'nmeSpawner26',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner27': {'DIM': (16, 16),
                  'POS': (1072, 432),
                  'name': 'nmeSpawner27',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner28': {'DIM': (16, 16),
                  'POS': (1072, 496),
                  'name': 'nmeSpawner28',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner29': {'DIM': (16, 16),
                  'POS': (1072, 560),
                  'name': 'nmeSpawner29',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner3': {'DIM': (16, 16),
                 'POS': (64, -112),
                 'name': 'nmeSpawner3',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner30': {'DIM': (16, 16),
                  'POS': (1008, 576),
                  'name': 'nmeSpawner30',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner31': {'DIM': (16, 16),
                  'POS': (944, 576),
                  'name': 'nmeSpawner31',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner32': {'DIM': (16, 16),
                  'POS': (880, 576),
                  'name': 'nmeSpawner32',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner33': {'DIM': (16, 16),
                  'POS': (816, 576),
                  'name': 'nmeSpawner33',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner34': {'DIM': (16, 16),
                  'POS': (752, 576),
                  'name': 'nmeSpawner34',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner35': {'DIM': (16, 16),
                  'POS': (688, 576),
                  'name': 'nmeSpawner35',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner36': {'DIM': (16, 16),
                  'POS': (624, 576),
                  'name': 'nmeSpawner36',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner37': {'DIM': (16, 16),
                  'POS': (560, 576),
                  'name': 'nmeSpawner37',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner38': {'DIM': (16, 16),
                  'POS': (496, 576),
                  'name': 'nmeSpawner38',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner39': {'DIM': (16, 16),
                  'POS': (432, 576),
                  'name': 'nmeSpawner39',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner4': {'DIM': (16, 16),
                 'POS': (128, -112),
                 'name': 'nmeSpawner4',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner40': {'DIM': (16, 16),
                  'POS': (368, 576),
                  'name': 'nmeSpawner40',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner41': {'DIM': (16, 16),
                  'POS': (304, 576),
                  'name': 'nmeSpawner41',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner42': {'DIM': (16, 16),
                  'POS': (240, 576),
                  'name': 'nmeSpawner42',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner43': {'DIM': (16, 16),
                  'POS': (176, 576),
                  'name': 'nmeSpawner43',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner44': {'DIM': (16, 16),
                  'POS': (112, 576),
                  'name': 'nmeSpawner44',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner45': {'DIM': (16, 16),
                  'POS': (48, 576),
                  'name': 'nmeSpawner45',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner46': {'DIM': (16, 16),
                  'POS': (-16, 576),
                  'name': 'nmeSpawner46',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner47': {'DIM': (16, 16),
                  'POS': (-80, 576),
                  'name': 'nmeSpawner47',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner48': {'DIM': (16, 16),
                  'POS': (-128, 512),
                  'name': 'nmeSpawner48',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner49': {'DIM': (16, 16),
                  'POS': (-128, 448),
                  'name': 'nmeSpawner49',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner5': {'DIM': (16, 16),
                 'POS': (192, -112),
                 'name': 'nmeSpawner5',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner50': {'DIM': (16, 16),
                  'POS': (-128, 384),
                  'name': 'nmeSpawner50',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner51': {'DIM': (16, 16),
                  'POS': (-128, 320),
                  'name': 'nmeSpawner51',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner52': {'DIM': (16, 16),
                  'POS': (-128, 256),
                  'name': 'nmeSpawner52',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner53': {'DIM': (16, 16),
                  'POS': (-128, 192),
                  'name': 'nmeSpawner53',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner54': {'DIM': (16, 16),
                  'POS': (-128, 128),
                  'name': 'nmeSpawner54',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner55': {'DIM': (16, 16),
                  'POS': (-128, 64),
                  'name': 'nmeSpawner55',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner56': {'DIM': (16, 16),
                  'POS': (-128, 0),
                  'name': 'nmeSpawner56',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner57': {'DIM': (16, 16),
                  'POS': (-128, -112),
                  'name': 'nmeSpawner57',
                  'offsetkey': 'nmeSpawner',
                  'scripts': 'nmeSpawner',
                  'sprites': 'nmeSpawner',
                  'tangible': False},
 'nmeSpawner6': {'DIM': (16, 16),
                 'POS': (256, -112),
                 'name': 'nmeSpawner6',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner7': {'DIM': (16, 16),
                 'POS': (320, -112),
                 'name': 'nmeSpawner7',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner8': {'DIM': (16, 16),
                 'POS': (384, -112),
                 'name': 'nmeSpawner8',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'nmeSpawner9': {'DIM': (16, 16),
                 'POS': (448, -112),
                 'name': 'nmeSpawner9',
                 'offsetkey': 'nmeSpawner',
                 'scripts': 'nmeSpawner',
                 'sprites': 'nmeSpawner',
                 'tangible': False},
 'player0': {'DIM': (32, 32),
             'POS': (464, 224),
             'name': 'player0',
             'offsetkey': 'player',
             'scripts': 'player',
             'sprites': 'player',
             'tangible': False},
 'scythe0': {'DIM': (32, 16),
             'POS': (96, 16),
             'name': 'scythe0',
             'offsetkey': 'scythe',
             'scripts': 'scythe',
             'sprites': 'scythe',
             'tangible': False},
 'whip0': {'DIM': (96, 32),
           'POS': (0, 0),
           'name': 'whip0',
           'offsetkey': 'whip',
           'scripts': 'whip',
           'sprites': 'whip',
           'tangible': False}}