SCRIPTS = {'player': {'START:0': [['set', 'self', 'base_speed', '4'],
                        ['set', 'self', 'speed_stat', '0'],
                        ['set', 'self', 'base_attack', '1'],
                        ['set', 'self', 'attack_stat', '0'],
                        ['set', 'self', 'hp', '50'],
                        ['set', 'self', 'max_hp', '50'],
                        ['set', 'self', 'auto_healing', '1'],
                        ['set', 'self', 'auto_healing_per', '60'],
                        ['set', 'self', 'auto_healing_counter', '0'],
                        ['set', 'self', 'state', 'WALK'],
                        ['focus', 'ROOT', 'self'],
                        ['#',
                         'when',
                         'moving',
                         'to',
                         'red',
                         'pants',
                         'deluxe',
                         '2,',
                         'remove',
                         'these',
                         'lines',
                         'and',
                         'set',
                         'the',
                         'input',
                         'state',
                         'in',
                         'the',
                         'arcade',
                         'machine'],
                        ['set', 'self', '_input_name', 'PLAYER1']],
            'WALK:0': [['exec', 'updateAutoHeal'], ['exec', 'updateMovement']],
            'WALK:20': [['exec', 'WALK:0'], ['set', 'self', 'frame', '-1']],
            'updateAutoHeal': [['set',
                                'self',
                                'auto_healing_counter',
                                'self.auto_healing_counter',
                                '+',
                                '1'],
                               ['if',
                                'self.auto_healing_counter',
                                '>=',
                                'self.auto_healing_per'],
                               ['set', 'self', 'auto_healing_counter', '0'],
                               ['set',
                                'self',
                                'hp',
                                'self.hp',
                                '+',
                                'self.auto_healing'],
                               ['set',
                                'self',
                                'hp',
                                'min',
                                'self.hp',
                                'self.max_hp'],
                               ['endif']],
            'updateMovement': [['if', 'inpUP'],
                               ['set',
                                'self',
                                'y',
                                'self.y',
                                '-',
                                'self.speed_stat',
                                '-',
                                'self.base_speed'],
                               ['endif'],
                               ['if', 'inpDOWN'],
                               ['set',
                                'self',
                                'y',
                                'self.y',
                                '+',
                                'self.speed_stat',
                                '+',
                                'self.base_speed'],
                               ['endif'],
                               ['if', 'inpLEFT'],
                               ['set',
                                'self',
                                'x',
                                'self.x',
                                '-',
                                'self.speed_stat',
                                '-',
                                'self.base_speed'],
                               ['endif'],
                               ['if', 'inpRIGHT'],
                               ['set',
                                'self',
                                'x',
                                'self.x',
                                '-',
                                'self.speed_stat',
                                '+',
                                'self.base_speed'],
                               ['endif']]}}