SCRIPTS = {'exp': {'BYE:0': [['goodbye']],
         'COLLECT:0': [['set',
                        'self',
                        'calcx',
                        'player0.x',
                        '-',
                        'self.x',
                        '/',
                        '2'],
                       ['set',
                        'self',
                        'calcy',
                        'player0.y',
                        '-',
                        'self.y',
                        '/',
                        '2'],
                       ['set', 'self', 'x', 'self.x', '+', 'self.calcx'],
                       ['set', 'self', 'y', 'self.y', '+', 'self.calcy']],
         'COLLECT:12': [['set', 'self', 'state', 'BYE']],
         'EXP:0': [['set',
                    'self',
                    'calcx',
                    'player0.w',
                    '/',
                    '2',
                    '+',
                    'player0.x',
                    '-',
                    'self.x'],
                   ['set',
                    'self',
                    'calcy',
                    'player0.h',
                    '/',
                    '2',
                    '+',
                    'player0.y',
                    '-',
                    'self.y'],
                   ['if', 'abs', 'self.calcx', '<', 'self.dist'],
                   ['if', 'abs', 'self.calcy', '<', 'self.dist'],
                   ['set', 'self', 'state', 'COLLECT'],
                   ['endif'],
                   ['endif']],
         'START:0': [['set', 'self', 'state', 'EXP'],
                     ['set', 'self', 'dist', '64']]},
 'health_bar_segment': {'BLACK:0': [['exec', 'follow'],
                                    ['if',
                                     'player0.hp',
                                     '>',
                                     'self.lowerbound'],
                                    ['set', 'self', 'state', 'PINK'],
                                    ['endif']],
                        'PINK:0': [['exec', 'follow'],
                                   ['if', 'player0.hp', '>', 'self.upperbound'],
                                   ['set', 'self', 'state', 'RED'],
                                   ['endif'],
                                   ['if', 'player0.hp', '<', 'self.lowerbound'],
                                   ['set', 'self', 'state', 'BLACK'],
                                   ['endif']],
                        'RED:0': [['exec', 'follow'],
                                  ['if', 'player0.hp', '<', 'self.upperbound'],
                                  ['set', 'self', 'state', 'PINK'],
                                  ['endif']],
                        'START:0': [['set', 'self', 'state', 'RED'],
                                    ['set', 'self', 'number', ''],
                                    ['for', 'letter', 'self.name'],
                                    ['if',
                                     'letter',
                                     'in',
                                     'health_bar_segment'],
                                    ['break'],
                                    ['endif'],
                                    ['set',
                                     'self',
                                     'number',
                                     'self.number',
                                     '+',
                                     'letter'],
                                    ['endfor'],
                                    ['set',
                                     'self',
                                     'number',
                                     'int',
                                     'self.number'],
                                    ['set',
                                     'self',
                                     'upperbound',
                                     'player0.max_hp',
                                     '//',
                                     '17',
                                     '*',
                                     'self.number'],
                                    ['set',
                                     'self',
                                     'lowerbound',
                                     'player0.max_hp',
                                     '//',
                                     '17',
                                     '*',
                                     'self.number',
                                     '-',
                                     '1'],
                                    ['if', 'self.upperbound', '==', '0'],
                                    ['set', 'self', 'lowerbound', '0'],
                                    ['set', 'self', 'upperbound', '1'],
                                    ['endif'],
                                    ['set',
                                     'self',
                                     'off_x',
                                     'self.x',
                                     '-',
                                     'player0.x'],
                                    ['set',
                                     'self',
                                     'off_y',
                                     'self.y',
                                     '-',
                                     'player0.y']],
                        'follow': [['set',
                                    'self',
                                    'x',
                                    'player0.x',
                                    '+',
                                    'self.off_x'],
                                   ['set',
                                    'self',
                                    'y',
                                    'player0.y',
                                    '+',
                                    'self.off_y']]},
 'nme': {'FOLLOW:0': [['exec', 'followPlayer'],
                      ['img', 'self.image', '+', '_0']],
         'FOLLOW:10': [['exec', 'followPlayer'],
                       ['img', 'self.image', '+', '_1']],
         'FOLLOW:20': [['exec', 'followPlayer'],
                       ['img', 'self.image', '+', '_1'],
                       ['set', 'self', 'frame', '0']],
         'START:0': [['set', 'self', 'state', 'FOLLOW'],
                     ['set', 'self', 'image', 'skello'],
                     ['set', 'self', 'speed', '2'],
                     ['set', 'self', 'hp', '10'],
                     ['set', 'self', 'drops', 'exp0'],
                     ['if', 'COLLIDE?'],
                     ['set', 'self', 'state', 'WAIT'],
                     ['break'],
                     ['endif'],
                     ['set', 'self', 'tangible', '1']],
         'WAIT:0': [['if', 'not', 'COLLIDE?'],
                    ['set', 'self', 'state', 'FOLLOW'],
                    ['set', 'self', 'tangible', '1'],
                    ['endif']],
         'followPlayer': [['set', 'self', 'x_vel', '0'],
                          ['set', 'self', 'y_vel', '0'],
                          ['if', 'player0.x', '>', 'self.x'],
                          ['set', 'self', 'x_vel', 'self.speed'],
                          ['set', 'self', 'direction', '1'],
                          ['endif'],
                          ['if', 'player0.x', '<', 'self.x'],
                          ['set', 'self', 'x_vel', '0', '-', 'self.speed'],
                          ['set', 'self', 'direction', '-1'],
                          ['endif'],
                          ['if', 'player0.y', '>', 'self.y'],
                          ['set', 'self', 'y_vel', 'self.speed'],
                          ['endif'],
                          ['if', 'player0.y', '<', 'self.y'],
                          ['set', 'self', 'y_vel', '0', '-', 'self.speed'],
                          ['endif'],
                          ['if', 'self.x_vel', 'and', 'self.y_vel'],
                          ['if', 'RAND?'],
                          ['set', 'self', 'x_vel', 'self.speed'],
                          ['if', 'RAND?'],
                          ['set', 'self', 'x_vel', 'self.x_vel', '*', '-1'],
                          ['endif'],
                          ['break'],
                          ['endif'],
                          ['set', 'self', 'y_vel', 'self.speed'],
                          ['if', 'RAND?'],
                          ['set', 'self', 'y_vel', 'self.y_vel', '*', '-1'],
                          ['endif'],
                          ['break'],
                          ['endif'],
                          ['if', 'self.x_vel', 'nor', 'self.y_vel'],
                          ['set', 'self', 'y_vel', 'self.speed'],
                          ['if', 'RAND?'],
                          ['set', 'self', 'y_vel', 'self.y_vel', '*', '-1'],
                          ['endif'],
                          ['break'],
                          ['endif'],
                          ['if', 'self.y_vel', 'nor', 'self.x_vel'],
                          ['set', 'self', 'x_vel', 'self.speed'],
                          ['if', 'RAND?'],
                          ['set', 'self', 'x_vel', 'self.x_vel', '*', '-1'],
                          ['endif'],
                          ['break'],
                          ['endif']]},
 'nmeManager': {'START:0': [['#',
                             'this',
                             'will',
                             'be',
                             'where',
                             'we',
                             'script',
                             'the',
                             'spawns'],
                            ['exec', 'everyFour0']],
                'START:100': [],
                'START:1200': [['exec', 'everyFour3']],
                'START:1300': [],
                'START:1500': [['set', 'self', 'frame', '0']],
                'START:300': [['exec', 'everyFour1']],
                'START:400': [],
                'START:600': [['exec', 'everyFour2']],
                'START:700': [],
                'everyFour0': [['set',
                                'self',
                                'spawnNumber',
                                'self.frame',
                                '*',
                                '4',
                                '%',
                                '58'],
                               ['set',
                                'nmeSpawner',
                                '+',
                                'self.spawnNumber',
                                'spawn',
                                '1']],
                'everyFour1': [['set',
                                'self',
                                'spawnNumber',
                                'self.frame',
                                '*',
                                '4',
                                '+',
                                '1',
                                '%',
                                '58'],
                               ['set',
                                'nmeSpawner',
                                '+',
                                'self.spawnNumber',
                                'spawn',
                                '1']],
                'everyFour2': [['set',
                                'self',
                                'spawnNumber',
                                'self.frame',
                                '*',
                                '4',
                                '+',
                                '2',
                                '%',
                                '58'],
                               ['set',
                                'nmeSpawner',
                                '+',
                                'self.spawnNumber',
                                'spawn',
                                '1']],
                'everyFour3': [['set',
                                'self',
                                'spawnNumber',
                                'self.frame',
                                '*',
                                '4',
                                '+',
                                '3',
                                '%',
                                '58'],
                               ['set',
                                'nmeSpawner',
                                '+',
                                'self.spawnNumber',
                                'spawn',
                                '1']]},
 'nmeRelocator': {'COLLIDE': [['if', 'self.spawner'],
                              ['set', 'self', 'tangible', '0'],
                              ['set', 'self', 'state', 'WAIT'],
                              ['set', 'self', 'x', 'self.spawner.x'],
                              ['set', 'self', 'y', 'self.spawner.y'],
                              ['endif']],
                  'FOLLOW:0': [['set',
                                'self',
                                'x',
                                'player0.x',
                                '+',
                                'self.off_x'],
                               ['set',
                                'self',
                                'y',
                                'player0.y',
                                '+',
                                'self.off_y']],
                  'START:0': [['set', 'self', 'state', 'FOLLOW'],
                              ['set',
                               'self',
                               'off_x',
                               'self.x',
                               '-',
                               'player0.x'],
                              ['set',
                               'self',
                               'off_y',
                               'self.y',
                               '-',
                               'player0.y']]},
 'nmeSpawner': {'FOLLOW:0': [['exec', 'updateSpawn'],
                             ['set',
                              'self',
                              'x',
                              'player0.x',
                              '+',
                              'self.off_x'],
                             ['set',
                              'self',
                              'y',
                              'player0.y',
                              '+',
                              'self.off_y']],
                'START:0': [['set', 'self', 'state', 'FOLLOW'],
                            ['set',
                             'self',
                             'off_x',
                             'self.x',
                             '-',
                             'player0.x'],
                            ['set',
                             'self',
                             'off_y',
                             'self.y',
                             '-',
                             'player0.y'],
                            ['set', 'self', 'max_nme', '2'],
                            ['set', 'self', 'nme_number', '0'],
                            ['set', 'self', 'spawn', '0']],
                'updateSpawn': [['if', 'not', 'self.spawn'],
                                ['break'],
                                ['endif'],
                                ['set', 'self', 'spawn', '0'],
                                ['set', 'self', 'calc', '1'],
                                ['for', 'num', 'range', 'self.max_nme'],
                                ['if', 'not', 'self.calc'],
                                ['break'],
                                ['endif'],
                                ['set',
                                 'self',
                                 'nme_name',
                                 'self.name',
                                 '+',
                                 'nme',
                                 '+',
                                 'num'],
                                ['set',
                                 'self',
                                 'calc',
                                 'inworld',
                                 'self.nme_name'],
                                ['endfor'],
                                ['if',
                                 'not',
                                 'self.nme_name',
                                 'or',
                                 'self.calc'],
                                ['set', 'self', 'spawn', '1'],
                                ['break'],
                                ['endif'],
                                ['create',
                                 'nme0',
                                 'self.nme_name',
                                 'self.x',
                                 'self.y'],
                                ['set',
                                 'self.nme_name',
                                 'spawner',
                                 'self.name'],
                                ['set',
                                 'self',
                                 'nme_level',
                                 'self.frame',
                                 '/',
                                 '4500',
                                 '%',
                                 '3'],
                                ['set',
                                 'self',
                                 'nme_toggle',
                                 'self.frame',
                                 '/',
                                 '1500',
                                 '%',
                                 '3'],
                                ['if', 'self.nme_toggle', '==', '0'],
                                ['set',
                                 'self.nme_name',
                                 'image',
                                 'skello',
                                 '+',
                                 'self.nme_level'],
                                ['endif'],
                                ['if', 'self.nme_toggle', '==', '1'],
                                ['set',
                                 'self.nme_name',
                                 'image',
                                 'demon',
                                 '+',
                                 'self.nme_level'],
                                ['endif'],
                                ['if', 'self.nme_toggle', '==', '2'],
                                ['set',
                                 'self.nme_name',
                                 'image',
                                 'girl',
                                 '+',
                                 'self.nme_level'],
                                ['endif']]},
 'player': {'COLLIDE': [['if', 'self.spawner'],
                        ['if', 'related.state', '==', 'DEAD'],
                        ['break'],
                        ['endif'],
                        ['if', 'related.state', '==', 'HURT'],
                        ['if', 'related.frame', '<', '10'],
                        ['break'],
                        ['endif'],
                        ['endif'],
                        ['set', 'related', 'hp', 'related.hp', '-', '1'],
                        ['set', 'related', 'state', 'HURT'],
                        ['endif']],
            'HURT:0': [['exec', 'updateAutoHeal'],
                       ['exec', 'updateMovement'],
                       ['exec', 'updateWhip'],
                       ['exec', 'updateScythe']],
            'HURT:20': [['if', 'self.hp', '<=', '0'],
                        ['set', 'self', 'state', 'DEAD'],
                        ['break'],
                        ['endif'],
                        ['exec', 'WALK:0'],
                        ['set', 'self', 'frame', '-1'],
                        ['set', 'self', 'state', 'WALK']],
            'START:0': [['set', 'self', 'exp', '0'],
                        ['set', 'self', 'base_speed', '4'],
                        ['set', 'self', 'speed_stat', '0'],
                        ['set', 'self', 'base_attack', '1'],
                        ['set', 'self', 'attack_stat', '0'],
                        ['set', 'self', 'hp', '50'],
                        ['set', 'self', 'max_hp', '50'],
                        ['set', 'self', 'auto_healing', '1'],
                        ['set', 'self', 'auto_healing_per', '1000'],
                        ['set', 'self', 'auto_healing_counter', '0'],
                        ['set', 'self', 'state', 'WALK'],
                        ['focus', 'ROOT', 'self'],
                        ['set', 'self', 'whip_level', '1'],
                        ['set', 'self', 'whip_bonus_damage', '4'],
                        ['set', 'self', 'whip_per', '60'],
                        ['set', 'self', 'whip_counter', '0'],
                        ['set', 'self', 'scythe_level', '1'],
                        ['set', 'self', 'scythe_bonus_damage', '2'],
                        ['set', 'self', 'scythe_per', '50'],
                        ['set', 'self', 'scythe_counter', '0'],
                        ['set', 'self', 'scythe_dir', '0'],
                        ['#',
                         'when',
                         'moving',
                         'to',
                         'red',
                         'pants',
                         'deluxe',
                         '2,',
                         'remove',
                         'these',
                         'lines',
                         'and',
                         'set',
                         'the',
                         'input',
                         'state',
                         'in',
                         'the',
                         'arcade',
                         'machine'],
                        ['set', 'self', '_input_name', 'PLAYER1']],
            'WALK:0': [['exec', 'updateAutoHeal'],
                       ['exec', 'updateMovement'],
                       ['exec', 'updateWhip'],
                       ['exec', 'updateScythe']],
            'WALK:20': [['exec', 'WALK:0'], ['set', 'self', 'frame', '-1']],
            'updateAutoHeal': [['set',
                                'self',
                                'auto_healing_counter',
                                'self.auto_healing_counter',
                                '+',
                                '1'],
                               ['if',
                                'self.auto_healing_counter',
                                '>=',
                                'self.auto_healing_per'],
                               ['set', 'self', 'auto_healing_counter', '0'],
                               ['set',
                                'self',
                                'hp',
                                'self.hp',
                                '+',
                                'self.auto_healing'],
                               ['set',
                                'self',
                                'hp',
                                'min',
                                'self.hp',
                                'self.max_hp'],
                               ['endif']],
            'updateMovement': [['if', 'inpUP'],
                               ['set',
                                'self',
                                'y',
                                'self.y',
                                '-',
                                'self.speed_stat',
                                '-',
                                'self.base_speed'],
                               ['endif'],
                               ['if', 'inpDOWN'],
                               ['set',
                                'self',
                                'y',
                                'self.y',
                                '+',
                                'self.speed_stat',
                                '+',
                                'self.base_speed'],
                               ['endif'],
                               ['if', 'inpLEFT'],
                               ['set', 'self', 'direction', '-1'],
                               ['set',
                                'self',
                                'x',
                                'self.x',
                                '-',
                                'self.speed_stat',
                                '-',
                                'self.base_speed'],
                               ['endif'],
                               ['if', 'inpRIGHT'],
                               ['set', 'self', 'direction', '1'],
                               ['set',
                                'self',
                                'x',
                                'self.x',
                                '-',
                                'self.speed_stat',
                                '+',
                                'self.base_speed'],
                               ['endif']],
            'updateScythe': [['if', 'self.scythe_level', '==', '0'],
                             ['break'],
                             ['endif'],
                             ['set',
                              'self',
                              'scythe_counter',
                              'self.scythe_counter',
                              '+',
                              '1'],
                             ['if',
                              'self.scythe_counter',
                              '<',
                              'self.scythe_per'],
                             ['break'],
                             ['endif'],
                             ['set', 'self', 'scythe_counter', '0'],
                             ['if', 'self.scythe_level'],
                             ['set',
                              'self',
                              'sname',
                              'self.name',
                              '+',
                              'scythe',
                              '+',
                              'self.scythe_dir'],
                             ['create',
                              'scythe0',
                              'self.sname',
                              'self.w',
                              '/',
                              '2',
                              '+',
                              'self.x',
                              'self.h',
                              '/',
                              '2',
                              '+',
                              'self.y'],
                             ['if', 'self.scythe_dir', '==', '0'],
                             ['set', 'self.sname', 'x_vel', '-2'],
                             ['set', 'self.sname', 'y_vel', '-2'],
                             ['endif'],
                             ['if', 'self.scythe_dir', '==', '1'],
                             ['set', 'self.sname', 'x_vel', '2'],
                             ['set', 'self.sname', 'y_vel', '-2'],
                             ['endif'],
                             ['if', 'self.scythe_dir', '==', '2'],
                             ['set', 'self.sname', 'x_vel', '2'],
                             ['set', 'self.sname', 'y_vel', '2'],
                             ['endif'],
                             ['if', 'self.scythe_dir', '==', '3'],
                             ['set', 'self.sname', 'x_vel', '-2'],
                             ['set', 'self.sname', 'y_vel', '2'],
                             ['endif'],
                             ['set',
                              'self',
                              'scythe_dir',
                              'self.scythe_dir',
                              '+',
                              '1'],
                             ['if', 'self.scythe_dir', '>=', '4'],
                             ['set', 'self', 'scythe_dir', '0'],
                             ['endif'],
                             ['endif']],
            'updateWhip': [['if', 'self.whip_level', '==', '0'],
                           ['break'],
                           ['endif'],
                           ['set',
                            'self',
                            'whip_counter',
                            'self.whip_counter',
                            '+',
                            '1'],
                           ['if', 'self.whip_counter', '<', 'self.whip_per'],
                           ['break'],
                           ['endif'],
                           ['set', 'self', 'whip_counter', '0'],
                           ['if', 'self.whip_level', '==', '1'],
                           ['set', 'self', 'wname', 'self.name', '+', 'whip0'],
                           ['create',
                            'whip0',
                            'self.wname',
                            'self.x',
                            '+',
                            'self.w',
                            'self.y'],
                           ['set',
                            'self.wname',
                            'direction',
                            'self.direction',
                            '*',
                            '-1'],
                           ['if', 'self.direction', '==', '-1'],
                           ['set',
                            'self.wname',
                            'x',
                            'self.wname.x',
                            '-',
                            'self.wname.w',
                            '-',
                            'self.w'],
                           ['endif'],
                           ['endif'],
                           ['if', 'self.whip_level', '==', '2'],
                           ['set', 'self', 'wname', 'self.name', '+', 'whip0'],
                           ['create',
                            'whip0',
                            'self.wname',
                            'self.x',
                            '+',
                            'self.w',
                            'self.y',
                            '-',
                            '16'],
                           ['set',
                            'self.wname',
                            'direction',
                            'self.direction',
                            '*',
                            '-1'],
                           ['if', 'self.direction', '==', '-1'],
                           ['set',
                            'self.wname',
                            'x',
                            'self.wname.x',
                            '-',
                            'self.wname.w',
                            '-',
                            'self.w'],
                           ['endif'],
                           ['set', 'self', 'wname', 'self.name', '+', 'whip1'],
                           ['create',
                            'whip0',
                            'self.wname',
                            'self.x',
                            '+',
                            'self.w',
                            'self.y',
                            '+',
                            '16'],
                           ['set',
                            'self.wname',
                            'direction',
                            'self.direction',
                            '*',
                            '-1'],
                           ['if', 'self.direction', '==', '-1'],
                           ['set',
                            'self.wname',
                            'x',
                            'self.wname.x',
                            '-',
                            'self.wname.w',
                            '-',
                            'self.w'],
                           ['endif'],
                           ['endif']]},
 'scythe': {'COLLIDE': [['if', 'self.spawner'],
                        ['set',
                         'self',
                         'hp',
                         'self.hp',
                         '-',
                         'player0.attack_stat',
                         '-',
                         'player0.base_attack',
                         '-',
                         'player0.scythe_bonus_damage'],
                        ['if', 'self.hp', '<=', '0'],
                        ['create',
                         'self.drops',
                         'self.name',
                         '+',
                         'drop',
                         'self.w',
                         '/',
                         '2',
                         '+',
                         'self.x',
                         'self.h',
                         '/',
                         '2',
                         '+',
                         'self.y'],
                        ['goodbye'],
                        ['endif'],
                        ['endif']],
            'SCYTHE0:0': [['set', 'self', 'timer', 'self.timer', '-', '1'],
                          ['if', 'self.timer', '<=', '0'],
                          ['goodbye'],
                          ['endif']],
            'SCYTHE0:12': [['exec', 'SCYTHE0:0'],
                           ['set', 'self', 'frame', '0']],
            'START:0': [['set', 'self', 'timer', '300'],
                        ['set', 'self', 'state', 'SCYTHE0'],
                        ['set', 'self', 'physics', '1']]},
 'whip': {'COLLIDE': [['if', 'self.spawner'],
                      ['set',
                       'self',
                       'hp',
                       'self.hp',
                       '-',
                       'player0.attack_stat',
                       '-',
                       'player0.base_attack',
                       '-',
                       'player0.whip_bonus_damage'],
                      ['if', 'self.hp', '<=', '0'],
                      ['create',
                       'self.drops',
                       'self.name',
                       '+',
                       'drop',
                       'self.w',
                       '/',
                       '2',
                       '+',
                       'self.x',
                       'self.h',
                       '/',
                       '2',
                       '+',
                       'self.y'],
                      ['goodbye'],
                      ['endif'],
                      ['endif']],
          'START:0': [['set', 'self', 'state', 'WHIP0']],
          'WHIP0:12': [['goodbye']],
          'WHIP1:12': [['goodbye']]}}