WORLDS = {'loadingzone': {'actors': ['whip0', 'nme0', 'exp0', 'scythe0'],
                 'background': 'gray',
                 'name': 'loadingzone',
                 'x_lock': None,
                 'y_lock': None},
 'root': {'actors': ['nmeManager0',
                     'nmeRelocator1',
                     'nmeRelocator0',
                     'nmeRelocator2',
                     'nmeRelocator3',
                     'player0',
                     'nmeSpawner1',
                     'nmeSpawner2',
                     'nmeSpawner3',
                     'nmeSpawner4',
                     'nmeSpawner5',
                     'nmeSpawner6',
                     'nmeSpawner7',
                     'nmeSpawner8',
                     'nmeSpawner9',
                     'nmeSpawner10',
                     'nmeSpawner11',
                     'nmeSpawner12',
                     'nmeSpawner13',
                     'nmeSpawner14',
                     'nmeSpawner15',
                     'nmeSpawner16',
                     'nmeSpawner17',
                     'nmeSpawner18',
                     'nmeSpawner19',
                     'nmeSpawner20',
                     'nmeSpawner21',
                     'nmeSpawner22',
                     'nmeSpawner23',
                     'nmeSpawner24',
                     'nmeSpawner25',
                     'nmeSpawner26',
                     'nmeSpawner27',
                     'nmeSpawner28',
                     'nmeSpawner29',
                     'nmeSpawner30',
                     'nmeSpawner31',
                     'nmeSpawner32',
                     'nmeSpawner33',
                     'nmeSpawner34',
                     'nmeSpawner35',
                     'nmeSpawner36',
                     'nmeSpawner37',
                     'nmeSpawner38',
                     'nmeSpawner39',
                     'nmeSpawner40',
                     'nmeSpawner41',
                     'nmeSpawner42',
                     'nmeSpawner43',
                     'nmeSpawner44',
                     'nmeSpawner45',
                     'nmeSpawner46',
                     'nmeSpawner47',
                     'nmeSpawner48',
                     'nmeSpawner49',
                     'nmeSpawner50',
                     'nmeSpawner51',
                     'nmeSpawner52',
                     'nmeSpawner53',
                     'nmeSpawner54',
                     'nmeSpawner55',
                     'nmeSpawner56',
                     'nmeSpawner0',
                     'nmeSpawner57',
                     'health_bar_segment0',
                     'health_bar_segment1',
                     'health_bar_segment2',
                     'health_bar_segment3',
                     'health_bar_segment4',
                     'health_bar_segment5',
                     'health_bar_segment6',
                     'health_bar_segment7',
                     'health_bar_segment8',
                     'health_bar_segment9',
                     'health_bar_segment10',
                     'health_bar_segment11',
                     'health_bar_segment12',
                     'health_bar_segment13',
                     'health_bar_segment14',
                     'health_bar_segment15',
                     'health_bar_segment16',
                     'health_bar_segment17'],
          'background': 'gray',
          'name': 'root',
          'x_lock': None,
          'y_lock': None}}