
// The following code was generated by the Red Pants Engine
// lets go baby
    
# include "actors.h"
# include <SDL2/SDL.h>
# include <SDL2/SDL_image.h>
Actor ACTORS[1001];
Actor TEMPLATES[1];
void actor_load() {
    add_actor(91, 464, 224, 32, 64, 0, 0, -1, -1, 90, 90, -1, -1, 17, 0, 1, 0, 0, 0, 0, 0);
    add_template_from_actorkey(0, 91);
}
