
// The following code was generated by the Red Pants Engine
// lets go baby

#include "imagedata.h"
#include "sprites.h"
#include <SDL2/SDL.h>

void spritesheet_load(SDL_Renderer* rend) {
    load_sprite(40, _chest, 32, 32, rend);
    load_sprite(49, _fireball0, 32, 48, rend);
    load_sprite(50, _fireball1, 32, 48, rend);
    load_sprite(51, _fireball2, 32, 32, rend);
    load_sprite(52, _fireball3, 32, 32, rend);
    load_sprite(53, _fireball4, 32, 32, rend);
    load_sprite(54, _fireball5, 64, 32, rend);
    load_sprite(55, _fireball56, 32, 32, rend);
    load_sprite(56, _fireball6, 64, 32, rend);
    load_sprite(57, _fireball7, 32, 32, rend);
    load_sprite(58, _fireball8, 32, 32, rend);
    load_sprite(59, _fireball9, 32, 32, rend);
    load_sprite(82, _orb0_0, 80, 80, rend);
    load_sprite(83, _orb0_1, 80, 80, rend);
    load_sprite(84, _orb0_2, 80, 80, rend);
    load_sprite(85, _orb0_3, 80, 80, rend);
    load_sprite(86, _orb0_4, 80, 80, rend);
    load_sprite(99, _rupee, 16, 16, rend);
    load_sprite(100, _scyth0_0, 32, 16, rend);
    load_sprite(101, _scyth0_1, 32, 16, rend);
    load_sprite(102, _scyth0_2, 32, 16, rend);
    load_sprite(103, _scyth0_3, 32, 16, rend);
    load_sprite(104, _scyth1_0, 64, 32, rend);
    load_sprite(105, _scyth1_1, 64, 32, rend);
    load_sprite(106, _scyth1_2, 64, 32, rend);
    load_sprite(107, _scyth1_3, 64, 32, rend);
    load_sprite(127, _whip0_0, 96, 32, rend);
    load_sprite(128, _whip0_1, 96, 32, rend);
    load_sprite(129, _whip0_2, 96, 32, rend);
    load_sprite(130, _whip0_3, 96, 32, rend);
    load_sprite(131, _whip1_0, 144, 48, rend);
    load_sprite(132, _whip1_1, 144, 48, rend);
    load_sprite(133, _whip1_2, 144, 48, rend);
    load_sprite(134, _whip1_3, 144, 48, rend);
    load_sprite(67, _gray, 64, 64, rend);
    load_sprite(42, _demon0_0, 64, 64, rend);
    load_sprite(43, _demon0_1, 64, 64, rend);
    load_sprite(44, _demon1_0, 64, 64, rend);
    load_sprite(45, _demon1_1, 64, 64, rend);
    load_sprite(46, _demon2_0, 64, 64, rend);
    load_sprite(47, _demon2_1, 64, 64, rend);
    load_sprite(61, _girl0_0, 64, 64, rend);
    load_sprite(62, _girl0_1, 64, 64, rend);
    load_sprite(63, _girl1_0, 64, 64, rend);
    load_sprite(64, _girl1_1, 64, 64, rend);
    load_sprite(65, _girl2_0, 64, 64, rend);
    load_sprite(66, _girl2_1, 64, 64, rend);
    load_sprite(91, _player0, 64, 64, rend);
    load_sprite(92, _player1, 64, 64, rend);
    load_sprite(110, _skello0_0, 64, 64, rend);
    load_sprite(111, _skello0_1, 64, 64, rend);
    load_sprite(112, _skello1_0, 64, 64, rend);
    load_sprite(113, _skello1_1, 64, 64, rend);
    load_sprite(114, _skello2_0, 64, 64, rend);
    load_sprite(115, _skello2_1, 64, 64, rend);
    add_offset(91, -16, 0);
    add_offset(92, -16, 0);
    add_sprite_map(90);
    add_to_sprite_map(90, 17, 0, 91);
    add_to_sprite_map(90, 22, 0, 91);
    add_to_sprite_map(90, 22, 10, 92);
}
