
    // The following code was generated by the Red Pants Engine
    // lets go baby

    # include "worlds.h"
    # include <SDL2/SDL.h>
    # include <SDL2/SDL_image.h>

    World WORLDS[1];
    void world_load() {
        add_world(0, 97, 67, 0, 0);
        add_actor_to_world(97, 91);
}
