
    // The following code was generated by the Red Pants Engine
    // lets go baby

    # include "worlds.h"
    # include <SDL2/SDL.h>
    # include <SDL2/SDL_image.h>

    World WORLDS[2];
    void world_load() {
        add_world(0, 147, 115, 0, 0);
        add_actor_to_world(147, 299);
        add_actor_to_world(147, 155);
        add_actor_to_world(147, 93);
        add_actor_to_world(147, 258);
        add_world(1, 245, 115, 0, 0);
        add_actor_to_world(245, 157);
        add_actor_to_world(245, 160);
        add_actor_to_world(245, 159);
        add_actor_to_world(245, 161);
        add_actor_to_world(245, 162);
        add_actor_to_world(245, 239);
        add_actor_to_world(245, 165);
        add_actor_to_world(245, 176);
        add_actor_to_world(245, 187);
        add_actor_to_world(245, 198);
        add_actor_to_world(245, 209);
        add_actor_to_world(245, 218);
        add_actor_to_world(245, 219);
        add_actor_to_world(245, 220);
        add_actor_to_world(245, 221);
        add_actor_to_world(245, 166);
        add_actor_to_world(245, 167);
        add_actor_to_world(245, 168);
        add_actor_to_world(245, 169);
        add_actor_to_world(245, 170);
        add_actor_to_world(245, 171);
        add_actor_to_world(245, 172);
        add_actor_to_world(245, 173);
        add_actor_to_world(245, 174);
        add_actor_to_world(245, 175);
        add_actor_to_world(245, 177);
        add_actor_to_world(245, 178);
        add_actor_to_world(245, 179);
        add_actor_to_world(245, 180);
        add_actor_to_world(245, 181);
        add_actor_to_world(245, 182);
        add_actor_to_world(245, 183);
        add_actor_to_world(245, 184);
        add_actor_to_world(245, 185);
        add_actor_to_world(245, 186);
        add_actor_to_world(245, 188);
        add_actor_to_world(245, 189);
        add_actor_to_world(245, 190);
        add_actor_to_world(245, 191);
        add_actor_to_world(245, 192);
        add_actor_to_world(245, 193);
        add_actor_to_world(245, 194);
        add_actor_to_world(245, 195);
        add_actor_to_world(245, 196);
        add_actor_to_world(245, 197);
        add_actor_to_world(245, 199);
        add_actor_to_world(245, 200);
        add_actor_to_world(245, 201);
        add_actor_to_world(245, 202);
        add_actor_to_world(245, 203);
        add_actor_to_world(245, 204);
        add_actor_to_world(245, 205);
        add_actor_to_world(245, 206);
        add_actor_to_world(245, 207);
        add_actor_to_world(245, 208);
        add_actor_to_world(245, 210);
        add_actor_to_world(245, 211);
        add_actor_to_world(245, 212);
        add_actor_to_world(245, 213);
        add_actor_to_world(245, 214);
        add_actor_to_world(245, 215);
        add_actor_to_world(245, 216);
        add_actor_to_world(245, 164);
        add_actor_to_world(245, 217);
        add_actor_to_world(245, 118);
        add_actor_to_world(245, 119);
        add_actor_to_world(245, 128);
        add_actor_to_world(245, 129);
        add_actor_to_world(245, 130);
        add_actor_to_world(245, 131);
        add_actor_to_world(245, 132);
        add_actor_to_world(245, 133);
        add_actor_to_world(245, 134);
        add_actor_to_world(245, 135);
        add_actor_to_world(245, 120);
        add_actor_to_world(245, 121);
        add_actor_to_world(245, 122);
        add_actor_to_world(245, 123);
        add_actor_to_world(245, 124);
        add_actor_to_world(245, 125);
        add_actor_to_world(245, 126);
        add_actor_to_world(245, 127);
}
